Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.box = "debian/bookworm64"
  config.vm.network "public_network", ip: "192.168.1.15"
  config.vm.provider "virtualbox" do |v|
    v.customize ['modifyvm', :id, '--nictype1', 'virtio']
    v.memory = 4096
  end
  config.vm.provision "shell",
    path: "bootstrap.sh"
end
